version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8073:8073"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    command: npm start